### ISSUE TITLE
Handle bash hash expansions

### ISSUE THREAD

**Issue by corby** [jenkinsci/token-macro-plugin#17]
The following token expansion does not work in Jenkins the token-macro-plugin:
${GIT_BRANCH#origin/}

If GIT_BRANCH=origin/master
then the expression should evaluate to:
master

**Comment by slide** [comment]
Please file issues in the Jenkins JIRA (https://issues.jenkins-ci.org)

**Comment by srl295** [comment]
@slide by the way  you can turn off the Issues feature in GitHub at the [settings page](https://github.com/jenkinsci/token-macro-plugin/settings)

**Comment by slide** [comment]
@srl295 The settings page is not accessible to me for some reason. I get a 404.

**Comment by srl295** [comment]
@slide it needs a repo owner. I should say 'for some value of of *you*'
