### ISSUE TITLE
BUILD_LOG_REGEX broken since 2.0

### ISSUE THREAD

**Issue by devminded** [jenkinsci/token-macro-plugin#24]
**Environment:**
- Ubuntu 16.04 LTS
- Token macro plugin 2.0
- Jenkins 2.7.4 (standalone)
- Build name setter plugin 1.6.5
- OpenJDK 1.8.0

**Log line:**
`<span class="timestamp"><b>14:58:18</b> </span>version: 1.0.0-SNAPSHOT`

**Using the "build name setter" plugin:**
`#${BUILD_NUMBER} - ${GIT_BRANCH}/${GIT_REVISION,length=6}/${BUILD_LOG_REGEX, regex="^.*?version: (.*?)$", substText="$1", maxMatches=1, showTruncatedLines=false }`

**Expected result (works with TMP 1.12.1):**
`#42 - origin/master/21dbab/1.0.0-SNAPSHOT`

**Actual result (using TMP 2.0):**
`#42 - origin/master/21dbab/${BUILD_LOG_REGEX, regex="^.*?version: (.*?)$", substText="$1", maxMatches=1, showTruncatedLines=false }`

**Comment by slide** [comment]
Please use jira at https://issues.jenkins-ci.org
