### ISSUE TITLE
Not able to use token transforms with more than one escaped character, or both # and % transforms together

### ISSUE THREAD

**Issue by nyarasha** [jenkinsci/token-macro-plugin#28]
I am not able to use token transforms # and % together in one call.
For example, ${TOKEN#\"%\,} returns the whole string including the first `"` and the last `,` characters instead of removing them.

I am also not able to use more than one escaped character in any one # or % call.
For example, ${TOKEN%\"\,} returns the entire string with the trailing `",` characters instead of removing them.

I took the use information for # and % from the documentation at https://wiki.jenkins-ci.org/display/JENKINS/Token+Macro+Plugin

This issue includes my test cases and results: http://stackoverflow.com/questions/43056099/setting-jenkins-build-name-from-package-json-version-value

**Comment by slide** [comment]
Please use https://issues.jenkinsci.org to file issues.
